include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    require_trailing_commas: false
    library_private_types_in_public_api: false
    sort_constructors_first: false
analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
  exclude:
    - "lib/onboarding/view/widgets/step_progress_indicator.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated_plugin_registrant.dart"
    - "lib/core/injections/injection_container.config.dart"
    - "test/**"
