name: cryptoplease
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  dartz: ^0.10.0
  intl: ^0.17.0
  retrofit: ^3.0.0
  retry: ^3.1.0
  dio: ^4.0.4
  dio_http_cache: ^0.3.0
  dio_smart_retry: ^1.0.3
  gap: ^2.0.0
  equatable: ^2.0.0
  json_annotation: ^4.4.0
  internet_connection_checker: ^0.0.1+2

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.0.6
  flutter_test: 
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0
  injectable_generator: ^1.1.2
  objectbox_generator: ^1.1.1
  retrofit_generator: ^3.0.0+2
  json_serializable: ^6.1.3
  freezed: ^0.14.2

dependency_overrides:
  analyzer: ^2.1.0
 
  http_parser: ^4.0.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.1
  meta: ^1.7.0
  path: ^1.8.1
  xml: ^5.2.0

flutter:
  uses-material-design: true
  generate: true
